import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Providers";
const inter = Inter({ subsets: ["latin"] });
import LandingHeader from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en" className="bg-[#f3f3f3]">
        <body className={`font-sans ${inter.className} bg-[#f3f3f3]`}>
        <Provider>
          <LandingHeader/>
          {children}
        </Provider>
      </body>
    </html>
  );
}
